apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-grafanadatasource
spec:
  datasource:
    access: proxy
    type: prometheus
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: Prometheus
    url: http://promloki-kube-prometheus-s-prometheus.monitoring:9090
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: thanos-grafanadatasource
spec:
  datasource:
    access: proxy
    type: prometheus
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: Thanos
    url: http://promloki-thanos-query.monitoring:9090
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-grafanadatasource
spec:
  datasource:
    access: proxy
    type: loki
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: Loki
    url: http://promloki.monitoring:3100
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
